<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/9
 * Time: 20:30
 */

namespace backend\models;


use yii\db\ActiveRecord;

class ArticleTypeModel extends ActiveRecord
{
    const SCENARIO_ADD = 'add';//添加场景
    const SCENARIO_SAVE = 'save';//修改场景
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%article_type}}';

    }
    public function rules()
    {
        return [
            // name, email, subject and body are required
            ['name', 'required', 'message' => '标题不能为空'],
            ['name', 'unique', 'message' => '标题已经存在','on'=>'add'],
            ['status', 'required', 'message' => '状态不能为空'],
        ];
    }
    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_ADD] = ['name','status'];
        $scenarios[self::SCENARIO_SAVE] = ['name','status'];
        return $scenarios;
    }

    //验证成功的时候处理数据
    public function afterValidate()
    {
        parent::afterValidate(); // TODO: Change the autogenerated stub
        if(empty($this->id)){
            $this->add_time=time();
        }else{
            $this->save_time=time();

        }
    }

}