<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/19
 * Time: 10:49
 */

namespace backend\models;


use yii\db\ActiveRecord;

class BannerModel extends ActiveRecord
{

    const SCENARIO_ADD = 'add';
    const SCENARIO_SAVE = 'save';
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%banner}}';

    }

    public function rules()
    {
        return [
            // name, email, subject and body are required
            [['status'], 'required', 'message' => '状态不能为空'],
            [['type'], 'required', 'message' => '类型不能为空'],
            [['name'], 'required', 'message' => '主题名字不能为空'],
            [['jump_url'], 'url', 'message' => '跳转链接不正确'],
            [['url'], 'required', 'message' => '图片没有上传','on'=>'add'],


        ];
    }
    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_ADD] = ['status', 'type','name','url','jump_url'];
        $scenarios[self::SCENARIO_SAVE] = ['status', 'type','name','url','jump_url'];
        return $scenarios;
    }
    //验证成功的时候处理数据
    public function afterValidate()
    {
        parent::afterValidate(); // TODO: Change the autogenerated stub
        if(empty($this->id)){
            $this->created_at=time();
        }else{
            $this->updated_at=time();

        }
    }

}