<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/2/4
 * Time: 10:02
 */

namespace backend\models;


use yii\db\ActiveRecord;

class ConfigModel extends ActiveRecord
{
    const SCENARIO_ADD = 'add';
    const SCENARIO_SAVE = 'save';
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%config}}';

    }
    public function rules()
    {
        return [
            // name, email, subject and body are required
            ['types', 'required', 'message' => '配置类型不能为空'],
            ['content', 'required', 'message' => '配置内容不能为空'],
        ];
    }
    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_ADD] = ['types', 'content'];
        $scenarios[self::SCENARIO_SAVE] = ['types','content','status'];
        return $scenarios;
    }

    //验证成功的时候处理数据
    public function afterValidate()
    {
        parent::afterValidate(); // TODO: Change the autogenerated stub
        if(empty($this->id)){
            $this->add_time=time();
        }else{
            $this->save_time=time();

        }
    }
}