<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/7/5
 * Time: 9:47
 */

namespace backend\models;

//ActiveRecord
use yii\db\ActiveRecord;

class PermissionsModel extends ActiveRecord
{
    const SCENARIO_ADD = 'add';
    const SCENARIO_SAVE = 'save';
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%permissions}}';

    }
    public function rules()
    {
        return [
            // name, email, subject and body are required
            ['name', 'required', 'message' => '管理用户组不能为空'],
            ['name', 'unique', 'message' => '管理用户组已经存在','on'=>'add'],
            [['access'], 'required', 'message' => '菜单不能为空'],
            [['access'], 'access',],
            [['info'], 'required', 'message' => '权限筛选不能为空'],

        ];
    }
    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_ADD] = ['name', 'access','info'];
        $scenarios[self::SCENARIO_SAVE] = ['name', 'access','info'];
        return $scenarios;
    }
    public function access()
    {
        if(!in_array('通用权限',$this->access)){
            $this->addError('info','通用权限,必须选择');
        }
        if(!in_array('获取菜单数据',$this->info)){
            $this->addError('info','获取菜单数据,必须选择');
        }
        if(!in_array('文件上传',$this->info)){
            $this->addError('info','文件上传,必须选择');
        }

    }
    //验证成功的时候处理数据
    public function afterValidate()
    {

        parent::afterValidate(); // TODO: Change the autogenerated stub
        $this->info=implode(';',(array)$this->info);
        $this->access=(implode(';',(array)$this->access));
    }
    //删除前调用
    public function beforeDelete()
    {
        parent::beforeDelete(); // TODO: Change the autogenerated stub
        if(!empty($this->id)&&$this->id==1){
            $this->addError('info','不能删除超级管理权限');
            return false;
        }else{
            return true;
        }
    }
}