<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/12
 * Time: 15:30
 */

namespace backend\models;


use yii\db\ActiveRecord;

class SubjectModel extends ActiveRecord
{
    const SCENARIO_ADD = 'add';
    const SCENARIO_SAVE = 'save';
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%subject}}';

    }

    public function rules()
    {
        return [
            // name, email, subject and body are required
            ['name', 'required', 'message' => '专题名字不能为空'],
            ['name', 'unique', 'message' => '专题已经存在'],
            [['status'], 'required', 'message' => '状态不能为空'],


        ];
    }
    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_ADD] = ['name', 'status'];
        $scenarios[self::SCENARIO_SAVE] = ['name','status'];
        return $scenarios;
    }
    //验证成功的时候处理数据
    public function afterValidate()
    {
        parent::afterValidate(); // TODO: Change the autogenerated stub
        if(empty($this->id)){
            $this->created_at=time();
        }else{
            $this->updated_at=time();

        }
    }
}