#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');

// 一定要包含这个文件进来，完成设置的@console的别名  
require(__DIR__ . '/../common/config/bootstrap.php');

$config = require(__DIR__ . '/config/main.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
